import './globals.css'
import { Work_Sans } from 'next/font/google'
import Header from "@/components/layout/Header";
import Providers from "./providers";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Work_Sans({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
      <Providers>
          <Header/>
          {children}
      </Providers>
      </body>
    </html>
  )
}
